name: Publish to PyPI

on:
  push:
    branches:
      - feature/PaquetePruebas

jobs:
  publish:
    name: Publish Python Package
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Navigate to package directory
      working-directory: local_test_package
      run: ls  # Opcional: verifica el contenido de la carpeta

    - name: Install dependencies
      working-directory: local_test_package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      working-directory: local_test_package
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      working-directory: local_test_package
      run: twine upload dist/*
